import HeaderPage from "@/components/layout/header/Header";
import SidebarDesktop from "@/components/layout/sidebar/Sidebar";
import type { Metadata } from "next";
// import { AuthContextProvider } from "../../../context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex w-full">
      <SidebarDesktop />
      <div className="flex flex-col bg-slate-50 pl-2 w-full">
        <HeaderPage />
        <div className="overflow-auto">{children}</div>
      </div>
    </main>

  );
}
