import HeaderPage from "@/components/layout/header/header";
import { Sidebar } from "@/components/layout/sidebar/sidebar";
import type { Metadata } from "next";
// import "../../app/global.css";

// import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex w-full">
      <Sidebar />
      <div className="flex flex-col bg-slate-50 p-2 gap-3 w-full">
        <HeaderPage />
        <div className="border shadow-md rounded-md  overflow-auto">
          {children}
        </div>
      </div>
    </main>
  );
}
